fix for deleting the last element
gobwas/hashring pull request #4
Opened 2023-12-14 11:57 UTC by hurd54

Сorrection of an error when removing the last element from the ring.

2023-12-14 19:00 UTC, serejkus requested changes

2023-12-15 06:34 UTC, hurd54 commented on ring_test.go
> +	}
Done

2023-12-15 06:39 UTC, hurd54 commented on ring.go
> +// this will allow you to have multiple hashring implementations
Using an alias for items object will make it possible to connect different implementations for the hash ring interface without using wrappers, but, in order to avoid prolonging the discussion and delaying the acceptance of the pull request, this change should be made separately.

2023-12-15 07:05 UTC, serejkus requested changes

2023-12-15 07:05 UTC, serejkus commented on ring_test.go
> +	}
This is a copy-paste of TestRingInsertDelete. What is the value of having these tests separate? Looks like Get() and following checks could be incorporated in TestRingInsertDelete.

2023-12-15 07:08 UTC, hurd54 commented on ring_test.go
> +	}
The TestRingInsertDelete test will give a more accurate signal of the problem.
But yes, I agree to combine them.

2023-12-15 07:17 UTC, serejkus approved these changes
LGTM, thank you!

2023-12-15 07:17 UTC, merged